### PR TITLE
Added restart on timer after the game ends

### PR DESCRIPTION
**Pull request by plin0009**
Coming from #5 , the server emits a `"winner"` event once the game engine finds a winner. Then, the server starts a 5-second countdown to emit the `"restart"` event and reset the players in the gameEngine.

Currently the `"winner"` handler is an empty function, ideally the winner name and a countdown would be drawn.
The `"restart"` handler tells `playersHandler` to clear the list of players.

I hope these changes help!

### CODE REVIEW

**Comment by LukeGarrigan** [comment]
Good work, I think it'd be better if we didn't recreate the player objects when the game ends, that way players will at least have the same colour. Let me know what your opinions are.

**Comment by plin0009** [comment]
Yes, I agree completely and I'll fix that.

**Comment by plin0009** [comment]
I've tested the changes I've made, and it works pretty nicely. Let me know what you think!

**Comment by LukeGarrigan** [comment]
Perfect @plin0009 &mdash; well done.

What we should consider next is displaying that game-ending count down on the UI, which should go hand in hand with https://github.com/LukeGarrigan/hacktober-race/issues/4

**Pull request merged**
